// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManager.Data;

#nullable disable

namespace TaskManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240430124649_simplifyMyTask")]
    partial class simplifyMyTask
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("TaskManager.Model.MyTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDone")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MyTasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Test 01",
                            IsDone = false,
                            Order = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Test 02",
                            IsDone = false,
                            Order = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Test 03",
                            IsDone = true,
                            Order = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Test 04",
                            IsDone = false,
                            Order = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
